name: Best in Class Education
markdown: kramdown
highlighter: null
exclude: [node_modules,Gruntfile.js,Gemfile,Gemfile.lock,package.json,config.rb,.gitignore]
relative_permalinks: false
baseurl: /bestinclass